### ISSUE TITLE
id3 -2 parameter not supported by id3

### ISSUE THREAD

**Issue by AndreyShamis** [snoopcatt/vksearch#7]
[ "$cfg_write_tags" -eq 1 ]  &&  id3  -2 -a "${song_artists[$i]}" -t "${song_titles[$i]}" "${song_artists[$i]} - ${song_titles[$i]}.mp3"

prints error
id3: invalid option -- '2'
usage: id3 -[tTaAycg] "value" file1 [file2...]
       id3 -d file1 [file2...]
       id3 -l file1 [file2...]
       id3 -L
       id3 -v
 -t   Modifies a Title tag
 -T   Modifies a Track tag
 -a   Modifies an Artist tag
 -A   Modifies an Album tag
 -y   Modifies a Year tag
 -c   Modifies a Comment tag
 -g   Modifies a Genre tag
 -l   Lists an ID3 tag
 -L   Lists all genres
 -R   Uses an rfc822-style format for output
 -d   Deletes an ID3 tag
 -h   Displays this help info
 -v   Prints version info

**Comment by kostett** [comment]
id3 version?

**Comment by AndreyShamis** [comment]
not relevant
